### ISSUE TITLE
Server.js failing to start

### ISSUE THREAD

**Issue by xavifuefer** [wbuchwalter/ng2-redux#18]
can't get the example to run.
```
npm install
tsd reinstall
npm start
```
and I'm getting:
```
> counter-redux@0.0.0 start /Users/xavi/Projects/ng2-redux/examples/counter
> node server.js

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/xavi/.nvm/versions/node/v4.2.2/bin/node" "/Users/xavi/.nvm/versions/node/v4.2.2/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! counter-redux@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the counter-redux@0.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the counter-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls counter-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xavi/Projects/ng2-redux/examples/counter/npm-debug.log
```

what am i doing wrong?

**Comment by wbuchwalter** [comment]
'EADDRINUSE' means that your port `3000` is already in use, either by another instance of server.js or something else (did you launch it twice in two terminals for example?).
I'm closing this issue as it is most likely not related to ng2-redux.
